# Generated by Django 5.2.5 on 2025-08-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
