# Generated by Django 5.2.5 on 2025-08-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auditlog_employee_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
    ]
